# Generated by Django 6.0.2 on 2026-06-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barbas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbas_imagen',
            name='archivo',
            field=models.ImageField(upload_to='barbas/'),
        ),
    ]
