# Generated by Django 6.0.2 on 2026-06-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cortes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cortes_imagen',
            name='archivo',
            field=models.ImageField(upload_to='Cortes/'),
        ),
    ]
