# Generated by Django 6.0.2 on 2026-06-10 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='barba',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='corte',
        ),
    ]
