# Generated by Django 6.0.2 on 2026-06-10 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0002_remove_carritoitem_barba_remove_carritoitem_corte'),
        ('Productos', '0003_rename_precio_productos_imagen_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Productos.productos_imagen'),
            preserve_default=False,
        ),
    ]
