# Generated by Django 6.0.2 on 2026-03-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaPrincipal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barberia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Barberia/')),
            ],
        ),
        migrations.DeleteModel(
            name='LugarBarberia',
        ),
    ]
