# Generated by Django 6.0.2 on 2026-03-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaPrincipal', '0002_barberia_delete_lugarbarberia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barberia',
        ),
    ]
