# Generated by Django 6.0.2 on 2026-06-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_imagen',
            name='Precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
