# Generated by Django 6.0.2 on 2026-06-10 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_productos_imagen_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos_imagen',
            old_name='Precio',
            new_name='precio',
        ),
    ]
